Feat: slideout on form page
MaddieLymei/AdoptADog pull request #9
Opened 2022-05-16 19:39 UTC by AndrewBB-BBD

Please test the slide out using different window sizes! :)

Click "What is required of me?" to open it. 

I also added a bit of modal logic. If you click "Contact me" then the modal will appear. You'll need to refresh the page to get rid of it.

2022-05-17 07:13 UTC, nikitasmal approved these changes
I really like the slide a lot it works on all the screen sizes for me and works smoothly. Thank you so much for all the effort on it @AndrewBB-BBD!! 

Could the modal maybe in the center of the screen?

2022-05-17 07:30 UTC, Nate-5 approved these changes

2022-05-17 08:34 UTC, MaddieLymei requested changes

2022-05-17 08:34 UTC, MaddieLymei commented on Client/adoptForm/adoptForm.html
> +        <button class="submitButton" id="contactMeButton">Contact me</button>
Maybe rename to "Apply" as the name. 

Also, "Go Home" after submission needs an action to show it is being hovered over or clicked.

2022-05-17 08:34 UTC, MaddieLymei commented on Client/adoptForm/adoptForm.js
> +function validateForm() {}
More form validation required.

2022-05-17 08:34 UTC, MaddieLymei commented on Client/adoptForm/adoptForm.css
> +.slideout {
Possible to have contact details of shelter on the LHS with the dogs name? Something to show what they are applying for?

2022-05-17 08:34 UTC, MaddieLymei commented on Client/adoptForm/adoptForm.css
>    overflow: auto;
css needs to be in the public folder/css/

2022-05-17 08:34 UTC, MaddieLymei commented on Client/adoptForm/adoptForm.html
> +        <button class="sliderLink" id="openSlideoutButton">
changes need to be put in views/adoptForm.html, watch out for my changes and work with them :-)

2022-05-17 08:34 UTC, MaddieLymei commented on Client/adoptForm/adoptForm.js
> -const telPattern = pattern="[0-9]{3}-[0-9]{2}-[0-9]{3}";
public/js/adoptForm.js needs these changes with my changes I have inserted please

2022-05-18 08:19 UTC, MaddieLymei approved these changes

2022-05-18 08:19 UTC, merged